license-check: true
vulnerability-check: true
fail-on-severity: "low"

fail-on-severity: low
allow-licenses:
  - GPL-3.0
  - BSD-3-Clause
  - MIT
  - Apache-2.0

deny-licenses:
  - LGPL-2.0
  - BSD-2-Clause

allow-ghsas: []
